"""Alembic environment.

Runs in two contexts:

* **At startup** — ``Database.init_schema`` calls ``command.upgrade(cfg,
  "head")`` and passes its already-configured engine via
  ``config.attributes["engine"]`` so migrations share the app's connect args
  (30s busy timeout matters with four containers on one SQLite file).
* **From the CLI** (``alembic -c alembic.ini ...``) — no engine attribute, so
  one is built from ``settings.db_path``.
"""

from __future__ import annotations

from alembic import context
from sqlalchemy import create_engine
from sqlmodel import SQLModel

from garmin_coach import models  # noqa: F401 — populate SQLModel.metadata
from garmin_coach.config import settings

# For `alembic revision --autogenerate` during development.
target_metadata = SQLModel.metadata

config = context.config


def _engine():
    engine = config.attributes.get("engine")
    if engine is not None:
        return engine
    return create_engine(
        f"sqlite:///{settings.db_path}",
        connect_args={"check_same_thread": False, "timeout": 30},
    )


def run_migrations_offline() -> None:
    context.configure(
        url=f"sqlite:///{settings.db_path}",
        target_metadata=target_metadata,
        literal_binds=True,
        render_as_batch=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    with _engine().connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            # SQLite ALTER support is limited; batch mode makes autogenerated
            # table alterations work via the copy-and-move pattern.
            render_as_batch=True,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
